version: '3'

services: 
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  node:
    container_name: instant_cart
    image: kiamco/instant-cart-api
    ports:
      - "8100:8000"
    depends_on:
      - mongo
volumes:
  mongo-db: